### ISSUE TITLE
Question: Is it possible to get installation path in post-install script?

### ISSUE THREAD

**Issue by DjSt3rios** [grandchild/linux_installer#4]
Basically I have a shared library which I included in the data folder, and I want to copy it to a folder Linux can read (like /usr/lib)

**Comment by grandchild** [comment]
Hey there, the install path is [passed as first argument to the hook script](https://github.com/grandchild/linux_installer/blob/4891d214/install_linux.go#L113). So you can use a hook like this to test it:

```shell
#!/usr/bin/env bash
echo This is the post-install hook. Installed to "$1".
```

**Comment by grandchild** [comment]
Be aware though that the script is not run as root, nor can it ask for a sudo password on the command line, if you run the GUI version. So this is of limited use for system paths like that.

You may consider using `LD_LIBRARY_PATH` when executing the application to set the path to a directory containing your libraries. This is what we did to solve the same problem.

**Comment by DjSt3rios** [comment]
@grandchild Thank you so much! And also big thanks for sharing all your hard work 😊
