### ISSUE TITLE
linux_installer for wsl?

### ISSUE THREAD

**Issue by ghost** [grandchild/linux_installer#5]
Hi there.

I would like to know if it would be possible to customize the installation of a linux distro that I will use in wsl(windows subsystem linux) with linux-installer. 

*Would it be possible to customize the installation of a linux distro that I will use in wsl(windows subsystem linux) with linux-installer?*

**Comment by grandchild** [comment]
Hi there,
I think you're misunderstanding what this project does. It's _not_ software for installing Linux. It's a builder to make installers that install application software _on_ a Linux system.

And while it would work on a orking WSL installation presumably, it can't install an OS image for WSL. There's plenty of tools for that. One that I know of is https://github.com/yuk7/wsldl
