### ISSUE TITLE
Linux builder Fails with error panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kcraghu** [grandchild/linux_installer#6]
sed -i 's/^  version: .\+$/  version: 0.0/' resources/config.yml
rm -f data-compressed/data.zip
rm -f Setup
mkdir -p data-compressed
cd data ; zip -r ../data-compressed/data.zip .
  adding: ExampleApp.sh (deflated 23%)
cp linux-installer Setup
./rice append --exec=Setup
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x57b326]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc00001e810?, {0xc0001fa400?, 0x2d?, 0x2c?}, 0x2c?)
	<autogenerated>:1 +0x26
archive/zip.readDirectoryEnd({0x690258, 0xc000125700}, 0x430)
	/usr/local/go/src/archive/zip/reader.go:581 +0xf5
archive/zip.(*Reader).init(0xc00014b570, {0x690258?, 0xc000125700}, 0x430)
	/usr/local/go/src/archive/zip/reader.go:124 +0x5c
archive/zip.NewReader({0x690258, 0xc000125700}, 0x430)
	/usr/local/go/src/archive/zip/reader.go:103 +0x5e
github.com/daaku/go%2ezipexe.zipExeReaderElf({0x6906b8?, 0xc000012248}, 0xb86d28)
	/Volumessd/work/linux_installer/vendor/github.com/daaku/go.zipexe/zipexe.go:128 +0x8b
github.com/daaku/go%2ezipexe.NewReader({0x6906b8, 0xc000012248}, 0x0?)
	/Volumessd/work/linux_installer/vendor/github.com/daaku/go.zipexe/zipexe.go:48 +0x98
github.com/daaku/go%2ezipexe.OpenCloser({0xc00001e780?, 0x2c?})
	/Volumessd/work/linux_installer/vendor/github.com/daaku/go.zipexe/zipexe.go:30 +0x57
github.com/daaku/go%2ezipexe.Open(...)
	/Volumessd/work/linux_installer/vendor/github.com/daaku/go.zipexe/zipexe.go:16
main.operationAppend({0xc000012238, 0x1, 0x10?})
	/Volumessd/work/linux_installer/vendor/github.com/GeertJohan/go.rice/rice/append.go:39 +0x418
main.main()
	/Volumessd/work/linux_installer/vendor/github.com/GeertJohan/go.rice/rice/main.go:42 +0x285
make: *** [Makefile:49: Setup] Error 2

**Comment by kcraghu** [comment]
Compiled in go version go1.20.5 linux/amd64

**Comment by grandchild** [comment]
@kcraghu can you confirm?

**Comment by grandchild** [comment]
For anyone reading this issue later and wanting to fix things:

What I did was
```shell
make clean
make vendor-refresh  # <- update dependencies
```
to update dependencies, and then e.g.
```
make run
```
to test.
